### ISSUE TITLE
npm run dev失败

### ISSUE THREAD

**Issue by YealZoy** [lanux/Vue-Admin#20]
+ node版本 v8.11.2
+ npm版本 5.6.0
+ 按你的要求修改了`/build/webpack.base.conf.js`

```javascript
{
        test: /\.js$/,
        loader: 'babel-loader',
        //exclude: /(node_modules|bower_components)/,
        // 注意elementUI的源码使用ES6需要解析
        include: [
          resolve('src'),
          resolve('test'),
          resolve('/node_modules/element-ui/src'),
          resolve('/node_modules/element-ui/packages'),
          resolve('/node_modules/vuex-router-sync')
        ]
}
```
+ npm run dev之后就报错了
+ 报错内容

```
E:\learn\Vue-Admin>npm run dev

> vue-admin-demo@1.0.0 dev E:\learn\Vue-Admin
> node build/dev-server.js

[HPM] Proxy created: /api  ->  http://127.0.0.1:3000
[HPM] Proxy rewrite rule created: "^/api" ~> ""


 ERROR  Failed to compile with 18 errors                                                                                                                        13:00:16

 error  in ./src/components/selectTree.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/components/selectTree.vue 7:0-251
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/sys/resource.vue
 @ ./src/pages/sys/resource.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/frame.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/frame.vue 11:0-240
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/sys/userAdd.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/sys/userAdd.vue 7:0-254
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/sys/user.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/sys/user.vue 11:0-251
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/sys/resource.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/sys/resource.vue 11:0-255
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/sys/menu.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/sys/menu.vue 11:0-251
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/sys/role.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/sys/role.vue 11:0-251
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/login.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/login.vue 11:0-246
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/dashboard.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/dashboard.vue 11:0-249
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/panel.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/components/panel.vue 11:0-245
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/resetPwd.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/resetPwd.vue 7:0-249
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/App.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/App.vue 11:0-238
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./node_modules/element-ui/packages/select/src/select-dropdown.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./node_modules/element-ui/packages/select/src/select-dropdown.vue 7:0-242
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/selectTree.vue
 @ ./src/components/selectTree.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/sys/resource.vue
 @ ./src/pages/sys/resource.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/404.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/components/404.vue 11:0-244
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/sideMenu.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/components/sideMenu.vue 11:0-249
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/subMenu.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/components/subMenu.vue 11:0-248
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/sideMenu.vue
 @ ./src/components/sideMenu.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/layout/header.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/layout/header.vue 11:0-252
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/layout/footer.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (E:\learn\Vue-Admin\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (E:\learn\Vue-Admin\node_modules\prettier\index.js:10370:12)
    at E:\learn\Vue-Admin\node_modules\prettier\index.js:31115:15
    at Object.format (E:\learn\Vue-Admin\node_modules\prettier\index.js:31134:12)
    at Object.module.exports (E:\learn\Vue-Admin\node_modules\vue-loader\lib\template-compiler\index.js:80:23)

 @ ./src/pages/layout/footer.vue 11:0-253
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:9000

```

**Comment by lanux** [comment]
给个版本号吧 
         resolve('/node_modules/.1.4.8@element-ui/src'),
          resolve('/node_modules/.1.4.8@element-ui/packages'),
          resolve('/node_modules/.4.3.0@vuex-router-sync')
